apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  resourceVersion: "1024046"
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: localusers
    mappingMethod: claim
    name: localusers
    type: HTPasswd
